version: '3.8'

services:
  app:
    container_name: employee-app-${APP_ENV}
    image: chrisnazha/employee-directory:latest
    env_file:
      - .env
    ports:
      - '${APP_HOST_PORT}:${APP_PORT}'
