version: '3.8'

services:
  app:
    container_name: employee-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${APP_HOST_PORT}:${APP_PORT}'
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - type: bind
        source: ./databases/mongodb/data/${APP_ENV}
        target: /data/db
  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - ${REDIS_PORT}:6379
      - 8001:8001
    volumes:
        - type: bind
          source: ./databases/redis/data/${APP_ENV}
          target: /data
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD} --save 1200 32
